import type { StoreItem } from "./uni_types";

export const STORE_ITEMS: StoreItem[] = [
    { id: "bucket", name: "バケツ", emoji: "🪣", description: "海水にバケツを仕掛ける", baseCost: 7, cps: 0.2 },
    { id: "trap", name: "ウニカゴ", emoji: "🧺", description: "効率よく捕獲できる", baseCost: 70, cps: 0.8 },
    { id: "rod", name: "釣り竿", emoji: "🎣", description: "釣り竿で狙い撃ち！", baseCost: 350, cps: 3 },
    { id: "boat", name: "漁船", emoji: "🚢", description: "沖まで出て大量捕獲", baseCost: 1500, cps: 12 },
    { id: "factory", name: "ウニ工場", emoji: "🏭", description: "大量生産体制の確立", baseCost: 7000, cps: 45 },
    { id: "kingdom", name: "ウニ王国", emoji: "🌏", description: "全世界の🦀を支配する", baseCost: 35000, cps: 150 },

    { id: "drone", name: "漁業ドローン", emoji: "🚁", description: "自動でウニを探索", baseCost: 140000, cps: 400 },
    {
        id: "submarine",
        name: "深海潜水艦",
        emoji: "🛸",
        description: "深海のレアウニを捕獲",
        baseCost: 700000,
        cps: 1200,
    },
    { id: "lab", name: "ウニ研究所", emoji: "🔬", description: "効率を科学的に改善", baseCost: 3500000, cps: 3000 },
    { id: "clone", name: "ウニクローン装置", emoji: "🧬", description: "ウニを無限増殖", baseCost: 14000000, cps: 9000 },
    { id: "ai", name: "漁業AI", emoji: "🤖", description: "最適な漁を自動化", baseCost: 70000000, cps: 22000 },
    {
        id: "satellite",
        name: "衛星ネットワーク",
        emoji: "🛰️",
        description: "全海域を監視",
        baseCost: 350000000,
        cps: 60000,
    },
    {
        id: "portal",
        name: "海洋ポータル",
        emoji: "🌀",
        description: "別次元からウニを召喚",
        baseCost: 1400000000,
        cps: 150000,
    },
    {
        id: "time",
        name: "時間操作装置",
        emoji: "⏳",
        description: "未来のウニを先取り",
        baseCost: 7000000000,
        cps: 450000,
    },
    { id: "planet", name: "ウニ惑星", emoji: "🪐", description: "惑星規模で養殖", baseCost: 35000000000, cps: 1200000 },
    {
        id: "galaxy",
        name: "銀河漁業",
        emoji: "🌌",
        description: "銀河中のウニを収穫",
        baseCost: 140000000000,
        cps: 3000000,
    },
    {
        id: "dimension",
        name: "次元農場",
        emoji: "📦",
        description: "複数次元で同時生産",
        baseCost: 700000000000,
        cps: 7500000,
    },
    {
        id: "god",
        name: "ウニ神",
        emoji: "🦀✨",
        description: "存在するだけでウニが増える",
        baseCost: 3500000000000,
        cps: 18000000,
    },
    {
        id: "bigbang",
        name: "ビッグバン養殖",
        emoji: "💥",
        description: "宇宙ごと生成してウニを得る",
        baseCost: 14000000000000,
        cps: 45000000,
    },
    {
        id: "multiverse",
        name: "マルチバース漁業",
        emoji: "🧠",
        description: "全宇宙から収穫",
        baseCost: 70000000000000,
        cps: 120000000,
    },
];
